// Fragevorlage:
// {
//     category: "Toleranzen",
//     level: "N",
//     frage: "Frage",
//     fragebild: [],
//     fragebild_2: [],
//     antwort: "Antwort",
//     erklaerung: "Erklärung",
//     beispiel: "",
//     beispiel_bild: [],
//     beispiel_2: "",
//     beispiel_bild_2: []
// }

const questions_data = [
    {
        category: "Toleranzen",
        level: "N",
        frage: "Was versteht man unter dem **Nennmaß**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das in der Zeichnung angegebene Grundmaß. Also ohne Toleranzen.",
        erklaerung: "Das Nennmaß ist das Ausgangsmaß, auf das sich alle Toleranzen und Abmaße beziehen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Was gibt die Toleranz an?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Toleranzen beschreiben die maximal zulässigen Abweichungen vom Idealmaß oder der Idealform.",
        erklaerung: "Die Toleranz gibt den zulässigen Toleranzbereich eines Maßes an.\n\nFormel: Toleranz = Höchstmaß − Mindestmaß.",
        beispiel: "20 ± 0,1 ergibt eine Toleranz von 0,2 mm, also einen Bereich von 19,9 mm bis 20,1 mm.",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Warum werden Toleranzen benötigt?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Kein Fertigungsverfahren trifft ein Maß exakt. Deshalb müssen Toleranzen definiert werden, um die zulässigen Abweichungen festzulegen.",
        erklaerung: "Werkzeugverschleiß, Temperatur, Spannkräfte und Messunsicherheit sorgen dafür, dass jedes Werkstück ein klein wenig anders ausfällt.\nEine Toleranz legt fest, wie groß diese Abweichung sein darf, ohne dass das Teil seine Funktion verliert.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Wie groß sollte die Toleranz gewählt werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "So grob wie möglich, so fein wie nötig.",
        erklaerung: "Funktionstechnisch wichtige Maße benötigen meist engere Toleranzen.\nJe enger die Toleranz, desto höher können Fertigungs- und Prüfaufwand sein.\nNicht besonders wichtige Maße können über die Allgemeintoleranz toleriert werden.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Für welche Maße gelten Allgemeintoleranzen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Für alle Maße auf der Zeichnung ohne eigene Toleranzangabe.",
        erklaerung: "Sie gelten also für alle Maße, die nicht explizit mit einer anderen Toleranz versehen sind.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "In welche **4 Genauigkeitsklassen** sind Allgemeintoleranzen unterteilt?",
        fragebild: [],
        fragebild_2: [],
        antwort: "f (fein)\nm (mittel)\nc (grob)\nv (sehr grob)",
        erklaerung: "f = für präzise Teile, z. B. Werkzeugbau und Vorrichtungsbau.\nm = für mittlere Genauigkeit, z. B. allgemeiner Maschinenbau.\nc = für grobe Toleranzen, z. B. Stahl- und Lüftungsbau.\nv = für sehr grobe Toleranzen, z. B. Sandguss- und Schweißteile.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "In welche Gruppen werden Maß-Toleranzen unterteilt?",
        fragebild: [],
        fragebild_2: [],
        antwort: "* Allgemein-Toleranzen\n* Zahlen-Toleranzen\n* ISO-Toleranzen.",
        erklaerung: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Welches Toleranz-Symbol ist hier dargestellt?",
        fragebild: ["Media/rechtwinkeligkeit.png"],
        fragebild_2: [],
        antwort: "Die Rechtwinkeligkeitstoleranz.",
        erklaerung: "Die Toleranz legt fest, wie stark eine Fläche oder Linie vom exakt rechten Winkel abweichen darf. Sie benötigt eine Bezugsfläche oder Bezugslinie, auf die sich die Rechtwinkeligkeit bezieht.",
        beispiel: "Die rechte senkrechte Fläche muss innerhalb einer Toleranzzone von 0,1 mm rechtwinklig zur unteren waagrechten Fläche liegen.",
        beispiel_bild: ["Media/rechtwinkeligkeit_bsp.png"],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Welches Toleranz-Symbol ist hier dargestellt?",
        fragebild: ["Media/parallelität.png"],
        fragebild_2: [],
        antwort: "Parallelität.",
        erklaerung: "Sie beschreibt die Abweichung einer Linie oder Fläche von einer exakt parallelen Ausrichtung zu einer Bezugsfläche oder Bezugslinie. Die Parallelitätstoleranz legt fest, innerhalb welcher Toleranzzone die Linie oder Fläche liegen muss.",
        beispiel: "",
        beispiel_bild: ["Media/parallelität_bsp.png"],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Bei ISO-Toleranzen (z. B. 33k6) gibt es die Begriffe **Grundabmaß** und **Toleranzgrad**.\nWas versteht man unter diesen Begriffen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Grundabmaß:\nLage des Toleranzfeldes = k.\n\nToleranzgrad:\nGröße des Toleranzfeldes = 6.",
        erklaerung: "Das Grundabmaß sagt aus, in welcher Lage das Toleranzfeld liegt. Also wie weit weg von der Nulllinie die Toleranz beginnt. Im Beispiel 33k6 sind das +2 µm oberhalb der Nulllinie.\n\nDer Toleranzgrad sagt aus, wie groß das Toleranzfeld ist. Im Beispiel 33k6 ist der Toleranzbereich +16 µm.",
        beispiel: "Das Toleranzfeld liegt zwischen +2 µm und +18 µm. (+2 µm + +16 µm = +18 µm)\n\nDas Toleranzfeld ist in der Grafik blau dargestellt und beschreibt den zulässigen Toleranzbereich.",
        beispiel_bild: ["Media/ISO-Toleranz_33k6.png"],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Was stellt im Maß 22H7 die Zahl 7 dar?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Den Toleranzgrad.",
        erklaerung: "Je kleiner die Zahl, desto enger das Toleranzfeld. IT6 ist genauer als IT11.",
        beispiel: "20H7: Nennmaß 20 mm, Toleranzfeld H, Toleranzgrad 7. Die Zahl 7 sagt aus, wie groß die Toleranz ist, z. B. +21 µm.",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Was ist das Ist-Maß?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das am fertigen Werkstück gemessene Maß.",
        erklaerung: "Das Ist-Maß muss innerhalb der Toleranzgrenzen liegen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Wo auf der Zeichnung befindet sich die Angabe zur Allgemeintoleranz?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Im Schriftkopf, z. B. 'm'.",
        erklaerung: "Die Allgemeintoleranz gilt für alle Maße außer jene, die separat toleriert sind.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Was versteht man unter dem **Höchstmaß** (Go)?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das durch die Toleranz festgelegte Größtmaß.",
        erklaerung: "",
        beispiel: "Bei 20 ± 0,4 ist das Höchstmaß 20,4.",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Steht bei einer Zahlen-Toleranz das obere Abmaß oben oder unten?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das obere, größere Abmaß steht immer oben.",
        erklaerung: "",
        beispiel: "Bei 32 (+0,5 / -0,2) steht +0,5 oben.",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Wofür stehen die Toleranzklassen H, K, L bei Allgemeintoleranzen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Für die Toleranzklassen von Form- und Lagetoleranzen.",
        erklaerung: "Bei ISO 2768 stehen H, K und L für unterschiedliche Genauigkeitsklassen.",
        beispiel: "H = fein\nK = mittel\nL = grob",
        beispiel_bild: ["Media/zahlentoleranz1.png"],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Was ermitteln Formtoleranzen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die maximale Abweichung von der idealen Geometrieform.",
        erklaerung: "Zu den Formtoleranzen gehören:\n- Geradheit\n- Ebenheit\n- Rundheit\n- Zylinderform \n\nHinweis: Formtoleranzen benötigen keinen Bezug.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Was unterscheidet eine Lagetoleranz von einer Formtoleranz?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Formtoleranzen begrenzen die Abweichung der Form.\nLagetoleranzen begrenzen die Lage oder Ausrichtung eines Elements.",
        erklaerung: "Eine Formtoleranz beschreibt, wie stark eine Form von der idealen Form abweichen darf. Z. B. wie unrund darf eine Bohrung sein (Rundheit).\n\nEine Lagetoleranz beschreibt, wo ein Element liegen oder wie es ausgerichtet sein muss. Z. B. wo im Werkstück muss die Bohrung genau liegen (Positionstoleranz).",
        beispiel: "Parallelität legt fest, wie parallel eine Fläche oder Linie zu einem Bezug sein muss.",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Wie müssen Härteangaben auf technischen Zeichnungen toleriert werden?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Dem Härtewert ist eine möglichst große positive Toleranz anzuhängen.",
        erklaerung: "Der Härtewert auf einer Zeichnung ist stets der Mindesthärtewert. Deswegen benötigt man eine positive Toleranz.",
        beispiel: "58+4 HRC",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Warum werden Form- und Lagetoleranzen zusätzlich zu Maßtoleranzen eingesetzt?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Weil Maßtoleranzen Abweichungen der Form und Lage nicht begrenzen.",
        erklaerung: "Ein Bauteil kann im Maß liegen, aber dennoch unrund oder verzogen sein.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Was versteht man unter dem Mindestmaß?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das kleinste zulässige Maß eines Werkstücks oder einer Bohrung.",
        erklaerung: "Das tatsächliche Maß darf das Mindestmaß nicht unterschreiten.",
        beispiel: "Nennmaß 20 mm ± 0,1 mm ergibt ein Mindestmaß von 19,9 mm.",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Was versteht man unter einem Abmaß?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Abweichung eines Grenzmaßes vom Nennmaß.",
        erklaerung: "Es gibt ein oberes und ein unteres Abmaß. Das obere Abmaß gehört zum Höchstmaß, das untere Abmaß zum Mindestmaß.",
        beispiel: "Nennmaß 20 mm ± 0,1 mm:\n- oberes Abmaß = +0,1 mm,\n- unteres Abmaß = −0,1 mm.",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Was versteht man unter einer Toleranzzone?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Den Bereich zwischen Mindestmaß und Höchstmaß.",
        erklaerung: "Innerhalb dieser Zone darf das Ist-Maß liegen, damit das Werkstück maßlich zulässig ist.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Wie berechnet man die Toleranz?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Toleranz = Höchstmaß − Mindestmaß.",
        erklaerung: "",
        beispiel: "30,10 mm − 29,90 mm = 0,20 mm Toleranz.",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "N",
        frage: "Was bedeutet eine Maßangabe mit nur einem positiven Abmaß? Beispiel 20 +0,2",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die zulässige Abweichung liegt nur auf der positiven Seite des Nennmaßes.",
        erklaerung: "Das Maß darf nicht kleiner als das Nennmaß sein und darf höchstens um das positive Abmaß größer werden.",
        beispiel: "20 +0,2 bedeutet: Das Maß darf zwischen 20,000 mm und 20,200 mm liegen.",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "NV",
        frage: "Was bestimmt der Buchstabe bei einer ISO-Toleranz?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Lage des Toleranzfeldes zum Nennmaß.",
        erklaerung: "Der Buchstabe gibt die Grundabweichung beziehungsweise die Lage des Toleranzfeldes an. Bei Bohrungen werden Großbuchstaben, bei Wellen Kleinbuchstaben verwendet.\n\nH oder h grenzt dabei immer an das Nennmaß an, also mit 0 Abmaß.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Form- und Lagetoleranzen: Was ist ein Bezugselement?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Ein festgelegtes Element eines Werkstücks, auf das sich eine geometrische Toleranz bezieht.",
        erklaerung: "Ein Bezug kann beispielsweise eine Fläche, eine Achse oder eine Mittelebene sein.",
        beispiel: "",
        beispiel_bild: ["Media/bezugselemente.png"],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Was beschreibt die Geradheitstoleranz?",
        fragebild: ["Media/geradheit.png"],
        fragebild_2: [],
        antwort: "Wie stark eine Linie oder Achse von einer ideal geraden Linie abweichen darf.",
        erklaerung: "Die Geradheit begrenzt die Formabweichung von einer geraden Geometrie.",
        beispiel: "Beispielsweise muss die obere Schnittkante des Werkstücks auf 0,1 mm gerade sein.",
        beispiel_bild: ["Media/geradheit_bsp.png"],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Was beschreibt die Ebenheitstoleranz?",
        fragebild: ["Media/ebenheit.png"],
        fragebild_2: [],
        antwort: "Wie stark eine Fläche von einer ideal ebenen Fläche abweichen darf.",
        erklaerung: "Die gesamte Fläche muss innerhalb der festgelegten Toleranzzone liegen.",
        beispiel: "",
        beispiel_bild: ["Media/ebenheit_bsp.png"],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Was beschreibt die Rundheitstoleranz?",
        fragebild: ["Media/rundheit.png"],
        fragebild_2: [],
        antwort: "Wie stark ein kreisförmiger Querschnitt von einer idealen Kreisform abweichen darf.",
        erklaerung: "Die Rundheit ist eine Formtoleranz.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Was beschreibt die Zylinderformtoleranz?",
        fragebild: ["Media/zylinderform.png"],
        fragebild_2: [],
        antwort: "Wie stark die Mantelfläche eines Zylinders von einer idealen Zylinderform abweichen darf.",
        erklaerung: "Die Zylinderform berücksichtigt die gesamte zylindrische Oberfläche.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Was beschreibt eine Positionstoleranz?",
        fragebild: ["Media/position.png"],
        fragebild_2: [],
        antwort: "Sie legt fest, wie weit die tatsächliche Position eines Elements von seiner idealen Position abweichen darf.",
        erklaerung: "Sie wird beispielsweise zur genauen Festlegung der Lage von Bohrungen verwendet.",
        beispiel: "Die Maße 16 mm und 18 mm werden eckig umrahmt, um zu zeigen, dass die Allgemeintoleranzen auf diese Maße nicht gelten.",
        beispiel_bild: ["Media/positionstoleranz_bsp.png"],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Toleranzen",
        level: "V",
        frage: "Warum reicht eine Maßtoleranz bei einem Wellendurchmesser manchmal nicht aus?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Weil ein Maß innerhalb der Toleranz liegen kann, obwohl die tatsächliche Form trotzdem unzulässig ist.",
        erklaerung: "Eine Welle kann beispielsweise im Durchmessermaß liegen, aber trotzdem unrund oder gekrümmt sein.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },



    '------------------------------------------------------------------------------------------------------------------------------------------------------------------------------',







    {
        category: "Passungen",
        level: "NV",
        frage: "Was ist der Unterschied zwischen Toleranzen und Passungen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Toleranzen legen die zulässige Abweichung eines Maßes fest.\n\nEine Passung beschreibt das Zusammenwirken von zwei Bauteilen wie beispielsweise Bohrung und Welle.",
        erklaerung: "Bei einer Passung bestimmen die Toleranzen von Bohrung und Welle, ob Spiel, Übergang oder Übermaß entsteht.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Welche 3 Hauptarten von Passungen gibt es?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Spielpassung\n- Übergangspassung\n- Übermaßpassung.",
        erklaerung: "- Spiel = leicht beweglich.\n- Übergang = Spiel oder feste Verbindung möglich.\n- Übermaß = feste Verbindung.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Was kennzeichnet eine **Spielpassung**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das Mindestmaß der Bohrung ist größer als das Höchstmaß der Welle.",
        erklaerung: "Die Teile haben immer Spiel und lassen sich ohne Kraftaufwand ineinander bewegen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Was kennzeichnet eine **Übermaßpassung**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das Höchstmaß der Bohrung ist kleiner als das Mindestmaß der Welle.",
        erklaerung: "Die Welle ist immer größer als die Bohrung. Das Fügen erfordert Kraft oder Wärme.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Wann liegt eine **Übergangspassung** vor?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Wenn je nach Ist-Maß Spiel oder Übermaß entsteht.",
        erklaerung: "Die Toleranzfelder von Bohrung und Welle überschneiden sich. Es kann ein Spiel oder Übermaß, also eine Pressung, auftreten.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Was bedeutet ein **Großbuchstabe**, z. B. H, bei ISO-Toleranzen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Toleranzfeld einer Bohrung beziehungsweise eines Innenmaßes.",
        erklaerung: "Großbuchstaben stehen für Innenmaße, Kleinbuchstaben für Außenmaße beziehungsweise Wellen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Was bedeutet ein **Kleinbuchstabe**, z. B. f, bei Toleranzen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Toleranzfeld einer Welle beziehungsweise eines Außenmaßes.",
        erklaerung: "Kleinbuchstaben beschreiben Wellen- und Außenmaße im ISO-System.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Welches Abmaß hat der Toleranzfeldbuchstabe H?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das untere Abmaß ist exakt 0.",
        erklaerung: "Eine Bohrung mit dem Grundabmaß H hat als Mindestmaß genau das Nennmaß.\n\nZum Beispiel hat 20H7 ein Mindestmaß von 20,000 mm; das Höchstmaß liegt darüber.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Was beschreibt das System **Einheitsbohrung**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Bohrung hat das Grundabmaß H, die Passung wird über die Welle gewählt.",
        erklaerung: "Das spart Werkzeugkosten, da weniger Bohrer- und Reibahlengrößen benötigt werden. Die Welle lässt sich im Durchmesser leichter anpassen als die Bohrung.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Was beschreibt das System **Einheitswelle**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Welle hat das Grundabmaß h, die Passung wird über die Bohrung gewählt.",
        erklaerung: "Das ist ideal bei der Verwendung von Rundstählen ohne Nachbearbeitung. Rundstähle können beispielsweise in der Genauigkeitsklasse h6 gekauft werden. Die Bohrung muss dem Wellenmaß angepasst werden.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "V",
        frage: "Woher stammen Passungsempfehlungen für Wälzlager meistens?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Aus Herstellerkatalogen und technischen Tabellenwerken.",
        erklaerung: "Die passende Toleranzkombination hängt unter anderem von Belastung, Drehzahl und Betriebsbedingungen ab.\n\nHinweis: Bei Lagersitzen spielen auch Oberflächengüten eine große Rolle",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "NV",
        frage: "Welches Passungssystem ist im allgemeinen Maschinenbau am häufigsten in Verwendung?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Das System der Einheitsbohrung.",
        erklaerung: "Es wird bevorzugt, da man weniger verschiedene Reibahlen benötigt. Wellen-Durchmesser lassen sich leichter anpassen als Bohrungsdurchmesser.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Passungen",
        level: "NV",
        frage: "Begründe, warum im allgemeinen Maschinenbaudas Passungssystem **Einheitsbohrung** bevorzugt wird ?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Weil man weniger verschiedene Reibahlen benötigt. Wellen-Durchmesser lassen sich leichter anpassen als Bohrungsdurchmesser.",
        erklaerung: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },





    {
        category: "Passungen",
        level: "N",
        frage: "Was versteht man unter Spiel bei einer Passung?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Den Unterschied zwischen dem Maß der Bohrung und dem Maß der Welle, wenn die Bohrung größer ist.",
        erklaerung: "Spiel ermöglicht eine Bewegung zwischen Bohrung und Welle.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "N",
        frage: "Wie berechnet man das Mindestspiel?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Mindestspiel = Mindestmaß der Bohrung − Höchstmaß der Welle.",
        erklaerung: "Ist das Ergebnis positiv, ist auch im ungünstigsten Fall noch Spiel vorhanden.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "N",
        frage: "Wie berechnet man das Höchstspiel?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Höchstspiel = Höchstmaß der Bohrung − Mindestmaß der Welle.",
        erklaerung: "Das Höchstspiel ist das größtmögliche Spiel innerhalb der zulässigen Maße.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "N",
        frage: "Was versteht man unter Übermaß bei einer Passung?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Welle ist größer als die Bohrung.",
        erklaerung: "Dadurch entsteht eine Pressung. Zum Fügen ist Kraft oder je nach Anwendung eine Temperaturdifferenz erforderlich.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "V",
        frage: "Was bedeutet die Passungsangabe 20 H7/g6?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Eine Bohrung mit Toleranz H7 und eine Welle mit Toleranz g6, beide mit Nennmaß 20 mm.",
        erklaerung: "H bezeichnet das Toleranzfeld der Bohrung, g das Toleranzfeld der Welle. Die Zahlen 7 und 6 geben die jeweiligen IT-Toleranzgrade an.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Passungen",
        level: "N",
        frage: "Warum werden Bohrungen mit Großbuchstaben und Wellen mit Kleinbuchstaben bezeichnet?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Zur eindeutigen Unterscheidung zwischen **Innenmaß** und **Außenmaß** im ISO-Passungssystem.",
        erklaerung: "Großbuchstaben stehen für Bohrungen oder Innenmaße,\nKleinbuchstaben für Wellen oder Außenmaße.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "N",
        frage: "Eine Bohrung hat ein Mindestmaß von 20,00 mm und eine Welle ein Höchstmaß von 19,98 mm. Wie groß ist das Mindestspiel?",
        fragebild: [],
        fragebild_2: [],
        antwort: "0,02 mm",
        erklaerung: "Mindestspiel = 20,00 mm − 19,98 mm = 0,02 mm.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "N",
        frage: "Eine Bohrung hat ein Mindestmaß von 30,00 mm und ein Höchstmaß von 30,03 mm. Wie groß ist die Toleranz?",
        fragebild: [],
        fragebild_2: [],
        antwort: "0,03 mm",
        erklaerung: "Toleranz = 30,03 mm − 30,00 mm = 0,03 mm.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Passungen",
        level: "V",
        frage: "Wenn man eine Welle mit einem Zahnrad verbinden will, welche Passung ist empfehlenswert?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Laut Passungsempfehlungen im Tabellenbuch ist eine Übergangspassung mit dem Passungspaar H7/j6 empfehlenswert.",
        erklaerung: "Passungsempfehlungen sind in Tabellenbüchern zu finden.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    }
];

window.questionsData = questions_data;
